subprojects {
    apply plugin: 'java'
    apply plugin: 'idea'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    configurations.configureEach {
        resolutionStrategy.capabilitiesResolution.withCapability("com.google.collections:google-collections") {
            select("com.google.guava:guava:0")
        }

        resolutionStrategy.capabilitiesResolution.withCapability("com.google.guava:listenablefuture") {
            select("com.google.guava:guava:0")
        }
    }

    configurations {
        extra {
            transitive false
        }
    }

    jar {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE

        from {
            configurations.extra.collect {
                it.isDirectory() ? it : zipTree(it)
            }
        }

        archivesBaseName = 'RecipeManager'
    }

    repositories {
        mavenCentral()

        maven {
            name = "papermc"
            url = "https://repo.papermc.io/repository/maven-public/"
        }

        maven {
            name = "Spigot/Bukkit maven repo"
            url = "https://hub.spigotmc.org/nexus/content/groups/public/"
        }

        maven {
            name = "Jitpack"
            url = "https://jitpack.io"
        }

        mavenLocal()
    }

    test {
        useJUnitPlatform()
    }
}