subprojects {
    apply plugin: 'java'
    apply plugin: 'idea'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = 21
    }

    configurations.configureEach {
        resolutionStrategy.capabilitiesResolution.withCapability("com.google.collections:google-collections") {
            select("com.google.guava:guava:0")
        }

        resolutionStrategy.capabilitiesResolution.withCapability("com.google.guava:listenablefuture") {
            select("com.google.guava:guava:0")
        }
    }

    configurations {
        dependencyScope("extra")
        resolvable("extraClasspath") {
            extendsFrom extra
            transitive = false
        }
    }

    jar {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
        archiveBaseName = 'RecipeManager'

        from {
            configurations.extraClasspath.collect {
                it.isDirectory() ? it : zipTree(it)
            }
        }
    }

    repositories {
        mavenCentral()

        maven {
            name = "papermc"
            url = "https://repo.papermc.io/repository/maven-public/"
        }

        maven {
            name = "Spigot/Bukkit maven repo"
            url = "https://hub.spigotmc.org/nexus/content/groups/public/"
        }

        maven {
            name = "Jitpack"
            url = "https://jitpack.io"
        }

        mavenLocal()
    }

    test {
        useJUnitPlatform()
    }
}
